version: '2.0'

services:

  centos-7:
    command: ./build.sh
    environment:
      - WAREWULF_VERSION=4.4.1
    build:
      context: .
      dockerfile: Dockerfile.centos-7
    image: warewulf-builds:centos-7
    volumes:
      - /tmp/output:/tmp/output

  centos-8:
    command: ./build.sh
    environment:
      - WAREWULF_VERSION=4.4.1
    build:
      context: .
      dockerfile: Dockerfile.centos-8
    image: warewulf-builds:centos-8
    volumes:
      - /tmp/output:/tmp/output

  rhel-9:
    command: ./build.sh
    environment:
      - WAREWULF_VERSION=4.4.1
    build:
      context: .
      dockerfile: Dockerfile.rhel-9
    image: warewulf-builds:rhel-9
    volumes:
      - /tmp/output:/tmp/output